<?php
/**
 * @var $block \Mageplus\Booking\Controller\Adminhtml\QrCode\Import
 */
?>
<div class="import-category">
    <?php if (!$block->getIsReadonly()): ?>
        <div class="import-category_file">
            <form id="import-form" class="admin__fieldset" method="post" enctype="multipart/form-data">
                <?php echo $block->getBlockHtml('formkey')?>
                <div class="fieldset admin__field">
                    <label for="import_file" class="admin__field-label">
                        <span><?php /* @escapeNotVerified */ echo __('Import File') ?></span>
                    </label>
                    <div class="admin__field-control">
                        <div class="input-import-file">
                            <input type="file" id="import_link_file" name="project_file" class="input-file required-entry" />
                            <div class="message-information">
                                <p><?php echo __('Allowed file types: ');?><span style="">.csv</span></p>
                            </div>
                            <div>
                                <a href="<?= $block->getDefaultCsvPath() ?>">
                                    <?= __('Download sample file') ?>
                                </a>
                            </div>
                            <br>
                        </div>
                        <button type="button" name="import-submit" class="map-category-id primary" >
                            <?php echo __('Import');?>
                        </button>
                    </div>
                </div>
            </form>

            <script>
                require(
                    [
                        'jquery',
                        'mage/mage',
                        'loadingPopup'
                    ], function($){
                        $('#import-form').mage('form').mage('validation');
                        $('.map-category-id').on('click', function () {
                            if ($(':input[name="project_file"]').val()) {
                                $('body').loadingPopup({
                                    timeout: true
                                });
                                $(this.form).submit();
                            }
                        });
                    });
            </script>
        </div>
    <?php endif; ?>
</div>
